# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSzbTswtoXEJgy-YRXH80nqCY-pcSbhz
"""

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize , sent_tokenize
from collections import Counter

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

stop_words = set(stopwords.words('english'))

sentence = "In winters, I see you, In springtime I believe you, it's so good to be with you, my hope has come"

sentence = sentence.lower()

sentence

words = word_tokenize(sentence)
sentences = sent_tokenize(sentence)
filtered_words = [word for word in words if word not in stop_words]

stemmer = PorterStemmer()

stemmed_words = [stemmer.stem(word) for word in filtered_words]

word_counts = Counter(stemmed_words)

pos_tagged = nltk.pos_tag(stemmed_words)

pos_counts = Counter(tag for _, tag in pos_tagged)

#Print Results
print("Original Sentence")
print(sentence)
print("\nTokenized Words:")
print(words)
print("\nTokenized Sentences:")
print(sentences)
print("\nStopwords")
print(stop_words)
print("\nFiltered Words (without stopwords):")
print(filtered_words)
print("\nStemmed Words")
print(stemmed_words)
print("\nWord Counts")
print(word_counts)
print("\nPOS Tagged")
print(pos_tagged)
print("\nPOS Counts")
print(pos_counts)

